# -*- mode: ruby -*-
# vi: set ft=ruby :


memory = 1024
cpus = 2
hd = 40960

for i in 0 ... ARGV.length
    if ARGV[i] == 'up'
        $LOAD_PATH.unshift(File.expand_path("#{File.dirname(__FILE__)}/plugins/vagrant-host-shell/lib"))
        require "vagrant-host-shell"
    elsif ARGV[i] == '--memory'
        if i != ARGV.length-1
            memory = ARGV[i+1]
        end
    elsif ARGV[i] == '--cpus'
        if i != ARGV.length-1
            cpus = ARGV[i+1]
        end 
    elsif ARGV[i] == '--hd'
        if i != ARGV.length-1
            hd = ARGV[i+1]
        end
   end
end


# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu14.04"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = memory
    vb.cpus = cpus
  end

  ###################################################################
  # Next lines fixing error with github private repo authentication #
  # and used in git_sync recipe                                     #
  ###################################################################
  config.vm.provision :file, source: "~/.ssh/id_rsa", destination: "/home/vagrant/id_rsa"
  config.vm.provision :shell do |sh|
    sh.inline = "#!/bin/bash 
                mv /home/vagrant/id_rsa /root/.ssh/id_rsa 
                echo 'Host *\nStrictHostKeyChecking no' > /root/.ssh/config 
                chmod 400 /root/.ssh/id_rsa"
    sh.privileged = true
  end

  ###################################################################
  # Chef recipes                                                    #
  ###################################################################
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "./cookbooks"
    chef.add_recipe "install_pkgs"
    chef.add_recipe "git_sync"
  end

  ###################################################################
  # Local deploy & test                                             #
  ###################################################################
  config.vm.provision :shell do |sh|
    sh.inline = "cd /home/vagrant/geomongo
                ./scripts/local_deploy.sh
                curl http://geomongo/instance/status"
    sh.privileged = true
  end

  ###################################################################
  # Setting new storage size                                        #
  ###################################################################
  config.vm.provision :host_shell do |host_shell|
    if ARGV[ARGV.length-1] == 'up'
        puts hd
        host_shell.inline = './resize_storage.sh ' + hd.to_s
    end
  end  
end
